site_name: panderyx
site_description: Panderyx is a web app prepared for self-hosting. It lets you build automated ETL pipelines and analytical workflows on tabular data.
repo_url: https://github.com/sunnyfloyd/panderyx
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/sunnyfloyd">sunnyfloyd</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
