# Generated by Django 4.0.1 on 2022-02-26 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0002_alter_workflow_options_alter_workflow_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="tool name"
                    ),
                ),
                (
                    "x",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="x coordinate",
                    ),
                ),
                (
                    "y",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="y coordinate",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("url input", "URL Input"),
                            ("data input", "Data Input"),
                        ],
                        max_length=100,
                    ),
                ),
                ("config", models.JSONField(null=True)),
                ("data", models.URLField(null=True)),
                (
                    "inputs",
                    models.ManyToManyField(related_name="outputs", to="tools.Tool"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "name"],
            },
        ),
    ]
