# Generated by Django 4.0.1 on 2022-03-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_inputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='input_type',
        ),
    ]
