# Generated by Django 4.0.1 on 2022-03-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_tool_input_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='data',
        ),
    ]
