# Generated by Django 4.0.1 on 2022-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_remove_tool_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="type",
            field=models.CharField(
                choices=[("input_url", "URL Input")], default="input_url", max_length=30
            ),
            preserve_default=False,
        ),
    ]
