# Generated by Django 4.0.1 on 2022-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0005_tool_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="type",
        ),
        migrations.AlterField(
            model_name="tool",
            name="config",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
