# Generated by Django 4.0.1 on 2022-05-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_alter_workflow_options_alter_workflow_user"),
        ("tools", "0006_remove_tool_type_alter_tool_config"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tool",
            unique_together={("workflow", "name")},
        ),
    ]
