# Generated by Django 4.0.1 on 2022-02-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflow",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterField(
            model_name="workflow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
